name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e-tests:
    strategy:
      matrix:
        browser: [chromium, firefox]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # Checkout the repository code

      - uses: pnpm/action-setup@v3
        with:
          version: 8
        # Setup pnpm package manager

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
        # Setup Node.js with caching for pnpm

      - name: Clean install folders
        run: rm -rf node_modules ~/.pnpm-store
        # Clean any existing installs for a fresh start

      - name: Install dependencies
        run: pnpm install
        # Install all project dependencies

      - name: Cache Playwright binaries
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright
      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps
      - name: Run Playwright E2E Tests on ${{ matrix.browser }}
        run: pnpm exec playwright test --project ${{ matrix.browser }} --trace=on --reporter=line

      # Upload screenshots and traces for debugging
      - name: Upload Playwright test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts-${{ matrix.browser }}
          path: test-results/